sources:
  - name: Hello World
    handler:
      jsonSchema:
        baseUrl: 'https://raw.githubusercontent.com/alexmtch/github-eabbxs-9ycubb/main/schemas/responseSample.json'
        operations:          
          - type: Query
            field: myobject
            method: GET
            responseSchema: schemas/schema.json#/definitions/MyObject
